### ISSUE TITLE
Substitutions seem to be ignored when dynamic template data is given

### ISSUE THREAD

**Issue by black-silence** [sendgrid/sendgrid-php#1000]
### Issue Summary
I copied legacy template code to a dynamic template and added some handlebar stuff. The old substitutions we use in the legacy template (like :FIRSTNAME) are not replaced when sending mails, my new handlebar loops work fine. The code sending the legacy mail was only extended to include addDynamicTemplateDatas.

Are legacy substitutions disabled when using dynamic templates? If so, why is there no warning in the docs and from the client, api?

The php client puts all substitutions and dynamic_template_data into the "substitutions" personalization, is that a bug? It seems there is no way to put data into the "dynamic_template_data" member of a personalization, everything goes to substitutions (and some php doc there states those are legacy only)

### Steps to Reproduce
1. Send a dynamic template with "legacy" substitutions
2. Check substitutions do not work when not using handlebars syntax and there is NO warning
3. Expected: some kind of warning, at least in the api docs
4. Expected: api client uses the correct members and gives a warning when both types of substitutions are used

### Code Snippet
```php
$mail = new \SendGrid\Mail\Mail;
$mail->addSubstitutions(...);
$mail->addDynamicTemplateDatas(...);
```

### Technical details:
* sendgrid-php version: 7.8.1
* php version: 7.3

**Comment by childish-sambino** [comment]
There's documentation here about how to migrate the template itself which mentions substitution tags must be updated: https://sendgrid.com/docs/ui/sending-email/migrating-from-legacy-templates/

In this library, `addDynamicTemplateDatas` is basically just an alias for `addSubstitutions`. This makes it easier when migrating as you don't need to change all instances of `addSubstitutions` to `addDynamicTemplateDatas` because they're essentially the same.

The difference comes in when the payload is being serialized. It it's a dynamic template (ID prefix `d-`), then the dynamic template data/substitutions are placed in the `dynamic_template_data` param. Otherwise, under the `substitutions` param (similar comment here: https://github.com/sendgrid/sendgrid-php/issues/917#issuecomment-598255286).

Not sure what would be the best change to make in this library to help clarify this, if any, given the flexibility in the current implementation and not wanting to break others. Perhaps just some docs in the library to capture what I've laid out above?

**Comment by black-silence** [comment]
I think part of the problem is me starting with an empty dynamic template for testing, then manually copying the old template code over. When I ported the second template I used the UI copy function and there was info about updating the placeholders.

What could be done anyway:
* https://sendgrid.com/docs/for-developers/sending-email/migrating-from-v2-to-v3-mail-send/ add link to the template migration page, although it's not required template migration is certainly related, in my case it's required to migrate the templates because of some v3 API limits
* https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/ maybe add a note to the substitution block that legacy substitutions will not work in dynamic templates
* a warning when using both addSubstitution and addDynamicTemplateData in one Mail instance (possible BC break, unlikely you make this happen but maybe you have an idea)
