### ISSUE TITLE
Get all bounced e-mails with html content?

### ISSUE THREAD

**Issue by czmarcos** [sendgrid/sendgrid-php#1007]
I'm on Essentials plan and it looks like my shared pool is under some bad blacklists, my delivery rate which was 98% now is around 66%, which means that users cannot even find important transactional e-mail on their spam box. Imagine how bad is that..

Tried to contact support several times and told me that they could do nothing and their compliance team were already working on it (it has been 2 weeks and looks the same) and the only alternative solution would be to migrate do a dedicated ip server, which I obviously cannot afford.

So I'm looking for an alternative solution and thought about using an AWS SES as a backup server and try to resend all bounced e-mails through SES. The problem is that I'm already using the webhook to receive notifications of bounced e-mails, but I cannot receive the html content of them. If I could use it it would be very easy to send again with by back-up SES server.

Anyone have any experience whit this situation or have any ideia on how could I get all bounced e-mails and their html content?

**Comment by thinkingserious** [comment]
Hello @czmarcos,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
