### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support

### ISSUE THREAD

**Issue by typex-code** [sendgrid/sendgrid-php#1022]
Ok I get that I need to contact support but how the hell am I supposed to
I need to login to my account to submit a ticket and when I attempt to do so I get
> You are not authorized to access SendGrid, please contact Support

And it's an infinite loop.

Also tried emailing support@sendgrid.com, still no
> SENDGRID TICKET NOT CREATED

> Thanks for emailing SendGrid support. In an effort to make our Support responses smarter and more effective, we now require > you to log in to our online Help Center at support.sendgrid.com to create a support request.

> A ticket has not been created, and no one will reply to this email. Please go to support.sendgrid.com to create a support request.

**Comment by eshanholtz** [comment]
Hi @typex-code 

On the support site, you should be able to submit a ticket under "Trouble Logging In". It looks like this:
<img width="845" alt=" support" src="https://user-images.githubusercontent.com/28262845/99710721-c6278e80-2a55-11eb-9b14-5b41e3c2ae27.png">

**Comment by thinkingserious** [comment]
Hello @typex-code,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
