### ISSUE TITLE
Domain International Extension

### ISSUE THREAD

**Issue by jarscr** [sendgrid/sendgrid-php#1023]
### Issue Summary
Hi, I have issue sending email from domain with international extension, I don't find one solution for this.

Thanks

### Code Snippet
```php
          $mail->setFrom('sender@domain.co.cr' , 'Name');
            $mail->setReplyTo('sender@domain.co.cr' , 'Name');   
            $mail->addTo('me@gmail.com);
```

### Exception/Log
```
"$emailAddress" must be a valid email address. Got: sender@domain.co.cr 
```

### Technical details:
* sendgrid-php version:  7.9.1
* php version: 7.3

**Comment by thinkingserious** [comment]
Hello @jarscr,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
