### ISSUE TITLE
Send test email for a singlesend

### ISSUE THREAD

**Issue by LudovicFauchet** [sendgrid/sendgrid-php#1055]
Hello here,

I create a singlesends with the api but now i want to to create a send test mail for my client, like in the sendgrid back office here https://www.dropbox.com/s/9fmmwyfmwv6nl9k/Capture%20d%E2%80%99%C3%A9cran%202021-08-20%20%C3%A0%2009.46.54.png?dl=0

What endpoint to use, i don't find what i want in the api documentation i tried this endpoint https://sendgrid.api-docs.io/v3.0/send-test-email/marketing-campaigns-send-test but it doesn't work.

Cheers

**Comment by JenniferMah** [comment]
Hello @arifherdi16 ,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).

Thank you!

SendGrid DX Team
