### ISSUE TITLE
Header and footer dynamic templates [FEATURE]

### ISSUE THREAD

**Issue by martin-landhi** [sendgrid/sendgrid-php#1086]
Hi!

Are there a way to add header and footer as individual templates for email in order can modify the header for all emails?

Should be something that a template can be put inside another template.

**Comment by childish-sambino** [comment]
Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at [support.sendgrid.com](https://support.sendgrid.com/hc/en-us).
