### ISSUE TITLE
Call to undefined method SendGrid\Email::addTos()

### ISSUE THREAD

**Issue by gustavomanolo** [sendgrid/sendgrid-php#127]
Hi, i'm having a PHP Fatal error when trying to call the "addTos" function with the following message:
Call to undefined method SendGrid\Email::addTos()

Did yo remove this function in the latest release, or why is still in the README documentation?

Thanks

**Comment by eddiezane** [comment]
Thanks for letting us know this. The `addTos` method was moved to `addTo` and does not currently support arrays being passed in. Sorry if it caused you an issue. I'll be sure to get the README updated soon.

**Comment by Haritsinh** [comment]
Hey @eddiezane , i am little bit confused by reading this because now on 19 june 2019 i have used `addTos` method and it is perfectly working and you have said we have moved it to addTo.

 do you guys have added `addTos` method now or what because it is there in Mail class, And it is working perfectly in my code, i have arrived here by answer of [stackoverflow question](https://stackoverflow.com/questions/53401735/sendgrid-sending-to-multiple-recipients-using-api-v3-php-library-in-wordpress) in which user has referenced this so please clarify, thanks.

**Comment by eddiezane** [comment]
@Haritsinh it's been a few years since I've worked at SendGrid but maybe @thinkingserious can help.

**Comment by thinkingserious** [comment]
Hello @Haritsinh,

The current version of this SDK does have an `addTos` method as defined [here](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L380).

With best regards,

Elmer
