### ISSUE TITLE
Fatal error: Class 'Guzzle\Http\Message\RequestFactory' not found

### ISSUE THREAD

**Issue by JackIlPAZZO** [sendgrid/sendgrid-php#158]
I'm using the SendGrid library, I've put all in my scripts folder but when I execute my script I get this error:

Fatal error: Class 'Guzzle\Http\Message\RequestFactory' not found in /membri/poisson/scripts/sendgrid-php/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php on line 79
in the row 79 of the Client.php file there is:

$this->setRequestFactory(RequestFactory::getInstance());
But I don't understand what is wrong, because I follow the documentation correct. Someone have the same issue? What I doing wrong?

**Comment by pomle** [comment]
The SendGrid PHP lib has a dependency on Guzzle, more exactly on a very old version of Guzzle available here. https://github.com/guzzle/guzzle3

Pretty lazy.

**Comment by thinkingserious** [comment]
@JackIlPAZZO @pomle is correct, Guzzle is required for this library. 

@pomle If you would like to have more recent Guzzle support, please see [https://github.com/taz77/sendgrid-php](https://github.com/taz77/sendgrid-php). For now, we must maintain backwards support for Guzzle 3 due to the amount of users still using older version of PHP.
