### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by gsaqui** [sendgrid/sendgrid-php#175]
I'm looking at upgrading from 3.0 to 4.0 and noticed the warning about 

>One of the most notable changes is how addTo() behaves

I assume this is for people upgrading from 2.x to 3+.  Any chance you can change it to the following so every time I don't freak out?

```
One of the most notable changes from 2.x to 3.x onwards is how addTo() behaves
```

**Comment by idimensionz** [comment]
It is extra confusing because there is a Web API v2 and a Web API v3 (not just the PHP API **client library** in this repo which is what they just bumped from version 3 to 4).  It might have been a bit more helpful to include the "v3" in this repo name to indicate that this repo is specifically for the "Web API v3".

**Comment by thinkingserious** [comment]
Thanks for the feedback @gsaqui and @idimensionz,

We hope the new version of this library is clearer: https://github.com/sendgrid/sendgrid-php/tree/v3beta. If there is still confusion, please let us know.

With Best Regards,

Elmer
