### ISSUE TITLE
How can get the status of the mail?

### ISSUE THREAD

**Issue by helloarpitgshah** [sendgrid/sendgrid-php#202]
Hey,

I am using the Sendgrid API and I want to check if sent mail status with Success, Bounce, Pending, Spam, Bounce etc.

I have already written the code with autoload.php,

Can you please help me?

**Comment by idimensionz** [comment]
Hi,

You have a couple options.

First, you can use SendGrid's Webhooks to receive information on individual emails.  Documentation is available at https://sendgrid.com/docs/API_Reference/Webhooks/index.html. However, this means you need to build functionality to be able to accept webhook calls and store information sent by each call.   I have built this functionality into iDimensionz's Communiqué email service.  We're working on the UI to display that info to users.

You're other option is to use the Stats endpoints in SendGrid's WebAPI v3 to get those types of statistics about emails.  Documentation is available at https://sendgrid.com/docs/API_Reference/Web_API_v3/Stats/index.html . These are organized by date so it is more summary information rather than detailed information about specific emails.

I don't believe SendGrid's PHP WebAPI client has implemented the Stats endpoint yet.  I have started implementing the Stats endpoints in my PHP WebAPI v3 repo and they should be available soon.  You can checkout my repo at https://github.com/idimensionz/sendgrid-webapi-v3-php and play with some examples from my repo at  https://github.com/idimensionz/sendgrid-webapi-v3-examples.  I also setup a free Hipchat chat room to answer questions and discuss my API client which you can join at https://www.hipchat.com/gFqa8nAS0 .

**Comment by helloarpitgshah** [comment]
Thanks for your help :)

I really appreciated to your help.

**Comment by thinkingserious** [comment]
@idimensionz thanks for jumping in with a solution!

@helloarpitgshah thanks for reaching out and supporting SendGrid!

Our new library, to be out of beta shortly, supports all of our v3 Web API calls including the new v3 /mail/send: https://github.com/sendgrid/sendgrid-php/tree/v3beta
