### ISSUE TITLE
BCC with substitution

### ISSUE THREAD

**Issue by Petah** [sendgrid/sendgrid-php#237]
Adding a BCC to an email that uses substitution doesn't do the substitution for the BCCed person.

**Comment by thinkingserious** [comment]
Hello @Petah,

Thanks for reaching out to us!

Could you please provide the following:

1. A code snippet of the code in question
2. Please specify if you are using the current library or v3

Thanks!

With Best Regards,

Elmer

**Comment by danjesus** [comment]
I have the same problem.

Using current library.

```php
<?php
$email = new Email();

$email->addTo('person1@gmail.com')
            ->setFrom('person@gmail.com')
            ->setHtml("*|HTML|*")
            ->setSubject($subject)
           ->addSubstitution('*|HTML|*', "<p> Teste </p>");

(new SendGrid('api_key'))->send($email);
```
The substituion works for the recipient, but not for the bcc.

**Comment by thinkingserious** [comment]
Hello @Petah, @danjesus,

Within weeks, this library will be replaced with the v3 version: https://github.com/sendgrid/sendgrid-php/tree/v3beta

I don't think I'll be able to troubleshoot this issue on v2 before then, so I would suggest you migrate to v3, if possible, since we will no longer supporting the v2 library. 

The v3beta of this library is based on our new v3 /mail/send endpoint: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html. Hopefully, it solves this issue. If not, I will dig deeper.

With Best Regards,

Elmer

**Comment by danjesus** [comment]
Thanks @thinkingserious, I`ll try v3.

**Comment by xanmichaels** [comment]
Is this still a known issue? because I'm experiencing the same issues.  with Nuget SendGrid 9.0.12

**Comment by SendGridDX** [comment]
Hello @xanmichaels,

Would you mind creating a new issue along with the sample code?

Thanks!

Elmer
