### ISSUE TITLE
Fatal error: Class 'Guzzle\Http\Client'

### ISSUE THREAD

**Issue by zeeshan4971** [sendgrid/sendgrid-php#249]
i am using library  "version": "5.0.0",

Fatal error: Class 'Guzzle\Http\Client' not found

i have even installed composer and required this library

in my` sendgrid-php.php`

require 'vendor/autoload.php';

$apiKey = getenv('myAPi Key');
$sg = new SendGrid($apiKey);

**Comment by thinkingserious** [comment]
Hello @zeeshan4971,

You will need to create a new API, since the one you just posted has been compromised. In future public correspondence, please do not post your API Key.

The new library version no longer has a dependency on Guzzle. It is possible you are still using an older version of the library. Please try running `php composer.phar update`.

Thanks!
