### ISSUE TITLE
PHP compatibility for 5.4

### ISSUE THREAD

**Issue by getamach** [sendgrid/sendgrid-php#294]
Composer dependency of sendgrid-php asks for php 5.6. My current server is having the official php from Centos 7, which is still 5.4.x. Will the code break if I install manually?

**Comment by thinkingserious** [comment]
@getamach,

We do not support version 5.4.X, because it is now [end of life](http://php.net/supported-versions.php) and therefore we don't run tests against that version of PHP anymore. So I don't know if the code will break.

If you still want to use the library, I suggest you download the source and run the unit tests: https://github.com/sendgrid/sendgrid-php/blob/master/CONTRIBUTING.md#testing
