### ISSUE TITLE
Status code 100?

### ISSUE THREAD

**Issue by hifall** [sendgrid/sendgrid-php#391]
From time to time (~5%), using this sendgrid-php API to send an email fails. The status code I am seeing is: 100.

What does that mean? I can't find any documentation on this 100 status code.

**Comment by thinkingserious** [comment]
Hello @hifall,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by WadeShuler** [comment]
Not sure if this helps, and I see this issue is closed.

I have seen where the API responds with 2 codes, 100 and 202. This seems to be when setting the sendat time and/or batch of personalizations (array of personalization objects to send to many people in one go). I am not sure which one, or both. The way I checked the response code though, it still passed as it saw the 202.

Note: The email still sent

**Comment by thinkingserious** [comment]
Thanks for providing additional feedback @WadeShuler. If you continue to experience issues with a 100 status code, please reach out to our [support team](https://support.sendgrid.com/) as they are best equipped to assist with that type of issue. Thanks!
