### ISSUE TITLE
SendGrid code doesn't use PHP form values

### ISSUE THREAD

**Issue by kfm1607** [sendgrid/sendgrid-php#394]
#### Issue Summary

I have a website on Azure web apps. On the website, I have an HTML form with PHP handling. I'm using SendGrid services for receiving emails for the form details that visitors submit on my website. However, there seems to be an issue and I'm unable to make the PHP use the form values. The values do not work and I'm redirected to a blank version of the website. I don't understand what I'm doing wrong. 
Here's a link to the code I'm using: https://pastebin.com/vSCY55bW

#### Technical details:

* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @kfm1607,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
