### ISSUE TITLE
Unsubscribe Replacement Tag

### ISSUE THREAD

**Issue by cliftonscott** [sendgrid/sendgrid-php#402]
I want to use the [unsubscribe] replacement tag in my email footer. If I use the tag by itself, the entire subscribe URL it displayed. If I place the tag inside an anchor tag, the replacement tag is ignored and SendGrid appends the subscribe link below the footer.

**Ignored by SendGrid**
`<a href="[unsubscribe]">Unsubscribe</a>`

**SendGrid replaces with the subscribe URL
`[unsubscribe]`

I want to use the anchor tag to place the unsubscribe link within my footer, not below it.

**Comment by thinkingserious** [comment]
Hello @cliftonscott,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
