### ISSUE TITLE
missing sendgrid-php.php

### ISSUE THREAD

**Issue by nzhome** [sendgrid/sendgrid-php#406]
Why does .gitignore in this project hide sendgrid-php.php.  I spent 30 minutes looking high and low on the internet for this file. Where is it!?

**Comment by nzhome** [comment]
seems similiar to issues 340 and 341
who is maintaining this zip file?
https://sendgrid-open-source.s3.amazonaws.com/sendgrid-php/sendgrid-php.zip
 is it the latest and greatest?  why does everything have to be so hard?

**Comment by nzhome** [comment]
where is the best sendgrid-php.php   maintained? anyone got a link?

**Comment by thinkingserious** [comment]
Hello @nzhome,

It looks like the script we use to autogenerate that file is broken: https://github.com/sendgrid/sendgrid-php/blob/master/scripts/s3upload.sh#L10

We do have a fix coming soon [here](https://github.com/sendgrid/sendgrid-php/pull/405).

In the mean time, you can create sendgrid-php.php in your root directory and include the following:
```php
<?php
require __DIR__ . '/vendor/autoload.php';
?>
```

With Best Regards,

Elmer

**Comment by nzhome** [comment]
yeah I already did that an hour ago. I'm not a complete idiot. thanks.

**Comment by nzhome** [comment]
and why do you insist on a script generating such a simple, yet crucial, file?

**Comment by thinkingserious** [comment]
Hi @nzhome,

I apologize if you viewed my help as offensive, that was not my intent.

The person who created that script left the company a long time ago, so I'm not entirely sure why. My guess is that it was excluded since it's not necessary for those who are using composer. I think fix in the PR will resolve this issue moving forward. 

Thanks for taking the time to bring it to our attention.

With Best Regards,

Elmer
