### ISSUE TITLE
unsubscribe groups for transactional emails

### ISSUE THREAD

**Issue by bduave** [sendgrid/sendgrid-php#496]
Hi, I would like to know i can I set the url of the unsubscribe groups in a transactional emails? I saw in a documentation to go to settings and recipients but there is no that menu option there. how can I do?

**Comment by thinkingserious** [comment]
Hello @bduave,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
