### ISSUE TITLE
Break the testing class apart :: test/unit/SendGridTest.php

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#540]
All our tests are in one class. Break them up by type and use a base test class.

Make sure all the tests still run and report the same way as before.

https://codeclimate.com/github/sendgrid/sendgrid-php/test/unit/SendGridTest.php#issue_59f668408905d74fee00001e

**Comment by pxgamer** [comment]
Not claiming, but I'm happy to have a look at this. :+1:

**Comment by pxgamer** [comment]
I'm working on this in [feature/split-unit-tests](https://github.com/pxgamer/sendgrid-php/tree/feature/split-unit-tests) but for some reason I keep getting this error in Prism:
`error modifying response: via: detected request loop, header contains prism`

I'll continue working later when I'm on a native Linux OS, rather than LSFW at work.

**Comment by pxgamer** [comment]
To be honest, just seem to be getting quite a few issues with the Prism binary. 🤔 

I've done all the tests though. I may tidy up the structure though (which I've started with a few of them).

**Comment by pxgamer** [comment]
Ok, never mind. Looks like the test suite requires v1.5.0 of Prism, but the PHP installer in the test suite will download the latest version ([2.0.0-beta.2](https://github.com/stoplightio/prism/releases/tag/v2.0.0-beta.2)) which doesn't work with the OAI specification JSON.

Once I'd installed v1.5.0 it worked.
