### ISSUE TITLE
Timezone on API v3

### ISSUE THREAD

**Issue by Gmulti** [sendgrid/sendgrid-php#564]
Hi,

I have a problem with user profile.
I have all the time a forbidden access whereas I am well "full access" on the configuration of the API

`{"errors":[{"field":null,"message":"access forbidden"}]}`

So, I do not know where to get the "timezone" information from the account with API v3.

An idea ?
Thanks
Gmulti.

#### Technical details:

* sendgrid-php Version: master
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @Gmulti,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
