### ISSUE TITLE
Unable to send test mail on production AWS EC2

### ISSUE THREAD

**Issue by amrendraw3** [sendgrid/sendgrid-php#570]
#### Issue Summary

I am not able to send even [test mail provided here](https://github.com/sendgrid/sendgrid-php#hello-email) from production server that is an Ubuntu machine on AWS. I have open all inbound and outbound ports. I am able to send mail from localhost using the same code.
`echo "Send mail";
$response = $sg->client->mail()->send()->post($mail);
echo "Mail sent";`

I am getting **Send mail** as output only.

Mails are coming from this [test API](https://sendgrid.com/docs/API_Reference/api_v3.html) as well.

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
**sendgrid version:** "sendgrid/sendgrid": "~6.0"

**Comment by amrendraw3** [comment]
I enabled the error reporting and  found the following issue:
**Fatal error: Call to undefined function curl_init()**

I have to enable curl for my php installation. I made it working using installation command on Ubuntu machine.
`apt-get install php7.0-curl` (php 7.0)
`apt-get install php5-curl`  (php 5)

Restart nginx server: `sudo service nginx restart`

**Comment by thinkingserious** [comment]
Hello @amrendraw3,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
