### ISSUE TITLE
Email Attachments

### ISSUE THREAD

**Issue by geonewuser** [sendgrid/sendgrid-php#578]
Hello,

We are trying to send an email with an attachment less than 6MB

These are our php settings:

PHP Version 7.0.27

Local and Master Value memory_limit	256M

We are using  SendGrid Web API v3 via PHP

We get the following error:

PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 8519680 bytes) in /home/groupean/public_html/sendgrid-php/vendor/sendgrid/php-http-client/lib/Client.php on line 155

The only way we were able to make it work was by using ini_set('memory_limit', '-1'); but to us this is not a good solution.

Any suggestions?

Thanks.

**Comment by thinkingserious** [comment]
Hello @geonewuser,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
