### ISSUE TITLE
Better documenting the code

### ISSUE THREAD

**Issue by martijnmelchers** [sendgrid/sendgrid-php#598]
Hi! This library is awesome but the documentation isn't really great. 👎  so I had the idea of documenting the whole codebase (only inline for now) for release v7! I don't know what the release date for v7 is but I will try to get it all documented before the release. You can track my progress here: 
https://github.com/martijnmelchers/sendgrid-php/tree/v7
And see what I've done so far here: https://github.com/martijnmelchers/sendgrid-php/blob/v7/inline-documentation-progress.md

#### Technical details:

* sendgrid-php Version: v7 (Branch: v7)
* PHP Version: 5.2

**Comment by martijnmelchers** [comment]
Ok! So documenting the code is going great! But in the future (Starting V7) I would like to maintain the wiki. I will make a start in the `/wiki/` folder. I will add some examples that work with V7 and when functions deprecate we should probably keep them for the first minor release.

Example: V7 deprecates the function `getTest()`

Code in V7:
```php
/**
 * This function returns test
 *
 * @deprecated
 * @returns string
 */
public function getTest()
{
    return  $this->test;
}
````

This will make it show up like so:
![eecb448ed86bb5e9b2637eae8 1](https://user-images.githubusercontent.com/6060006/38551698-28c82f40-3cba-11e8-8302-01ceb1fd25c0.png)


Then in V7.1 it will be completely removed.


Any thoughts, ideas of anything I should document? @thinkingserious

**Comment by thinkingserious** [comment]
Hello @martijnmelchers,

Instead of using the wiki, we have been utilizing these documents:

[USAGE.md](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md)
This is autogenerated form our [Open API spec](https://github.com/sendgrid/sendgrid-oai), which also powers our [interactive docs](https://sendgrid.com/docs/API_Reference/api_v3.html). Similarly, we also generate the code in the `/examples` folder.

[USE_CASES.md](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md)
These are hand crafted and are designed to help developers achieve the most common use cases quickly.

Please take a look and let me know your thoughts on how the wiki can help.

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @martijnmelchers,

I'm really close to launching v7 and I've added phpDocs everywhere (Big thanks for your help getting this started, you saved me a bunch of time!), please re-submit your PR when I merge v7 to master. Thanks!

With Best Regards,

Elmer
