### ISSUE TITLE
Email send rate

### ISSUE THREAD

**Issue by acronwright** [sendgrid/sendgrid-php#600]
I have a system that requires up to 7000 email be sent. 
The content of the emails is stock market research and the clients are traders, business analysts etc.
The requirement is that all the emails be sent at the same time. Due to the different clients being on different infrastructure, we can't guarantee that they'll all receive the emails at the same time.
Using the batch email method what is the time difference between sending the 1st email and the 7000th email?
Trader X's email cannot be sent 30 minutes before trader Y's email as this will give trade X an unfair advantage.

**Comment by martijnmelchers** [comment]
This issue isn't specifically for this library but according to SendGrid their servers should be able to handle it easily. If you want a more specific answer you should try to contact the SendGrid support.

**Comment by acronwright** [comment]
Thanks for the reply. I've been trying to find this out and posted here as a last resort. Must be missing something but can't even find an email address for SendGrid.

**Comment by martijnmelchers** [comment]
@acronwright 

When you log in into your SendGrid account you can make a support ticket here: https://support.sendgrid.com/hc/en-us

The rest should speak for itself :)

**Comment by thinkingserious** [comment]
Hello @acronwright,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
