### ISSUE TITLE
Undelivered email details

### ISSUE THREAD

**Issue by bharatvaggu** [sendgrid/sendgrid-php#601]
Hi

Can you please tell me, how to get details of undelivered emails.

Thanks

**Comment by thinkingserious** [comment]
Hello @bharatvaggu,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
