### ISSUE TITLE
Anonymizing user data on request for GDPR compliance

### ISSUE THREAD

**Issue by mookman288** [sendgrid/sendgrid-php#621]
#### Issue Summary

After looking through the appropriate GDPR documents and explanations, I was wondering if you had features to implement a method to (or already have an example of how to) anonymize a user's records in SendGrid via the PHP API without deleting the anonymized data. 

For instance, pulling out email, first name, last name, etc. but leaving deliverability information. 

If not, is there a way to purge a user from SendGrid if I supply an email address via the PHP API? 

#### Steps to Reproduce

None this is a question/idea. 

#### Technical details:

None this is a question/idea.

**Comment by thinkingserious** [comment]
Hello @mookman288,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by mookman288** [comment]
@thinkingserious This isn't a problem, nor is this a non-library specific issue. Wouldn't this exclusively be covered by the PHP API's functionality on how to purge or anonymize data (that is to say, if I did this via cURL it would be different than PHP, since the PHP API has various support for the full SendGrid API?)

**Comment by thinkingserious** [comment]
Thanks for the clarification @mookman288,

I will leave this one open in case one of our all-star community members wants to give a crack at a PR.

I've also placed it on our internal backlog where additional +1's or comments will help it gain priority.

With Best Regards,

Elmer
