### ISSUE TITLE
Mail not being sent, but returns success?

### ISSUE THREAD

**Issue by alvarotrigo** [sendgrid/sendgrid-php#639]
I'm using the [V3 example for PHP](https://sendgrid.com/docs/Integrate/Code_Examples/v3_Mail/php.html) provided on the SendGrid API docs.

I'm getting the following response:

> Array
  | (
  | [0] => HTTP/1.1 202 Accepted
  | [1] => Server: nginx
  | [2] => Date: Thu, 05 Jul 2018 15:20:11 GMT
  | [3] => Content-Type: text/plain; charset=utf-8
  | [4] => Content-Length: 0
  | [5] => Connection: keep-alive
  | [6] => X-Message-Id: L2ALDEkiQ7i_WXCbhnyljA
  | [7] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io
  | [8] => Access-Control-Allow-Methods: POST
  | [9] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
  | [10] => Access-Control-Max-Age: 600
  | [11] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
  | [12] =>
  | [13] =>
  | )
  |  
 

However I receive no email at all on the `addTo` email:

```php
        $email->addTo("myemail@gmail.com", "Example User");
``` 

I on the activity panel in https://app.sendgrid.com/ I see 0 requests and 0 delivered.

**Comment by thinkingserious** [comment]
Hi @alvarotrigo,

There are [many reasons your email could have landed in the SPAM folder](https://sendgrid.com/blog/10-tips-to-keep-email-out-of-the-spam-folder). In this case, it may be because of the test data you are using and the age of your account. Try using some semi-realistic data and let me know how it goes.

With Best Regards,

Elmer

**Comment by alvarotrigo** [comment]
Yeap, I notice that.
Thanks for the info!
