### ISSUE TITLE
Is there a way to search for recipients based on a custom field?

### ISSUE THREAD

**Issue by mikoelsuperbeasto** [sendgrid/sendgrid-php#656]
hello!

This is a google translate from french, sorry!

After lot of research,  nothing relevant that works.

I am looking for a way to search all my contacts having an empty custom_fields value? In short, i need a way to do search with conditions, operator, etc.

There is no example in the documentation ... and, https://sendgrid.api-docs.io/v3.0/contacts-api-recipients/Create_Search%20with%20conditions, always returns me Request body not valid .

Some help?

**Comment by thinkingserious** [comment]
Hello @mikoelsuperbeasto,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
