### ISSUE TITLE
No longer possible to add substitution to the first personalization?

### ISSUE THREAD

**Issue by RaoulWernert** [sendgrid/sendgrid-php#676]
The !empty() checks (in version 6.0) where removed in the constructor of Mail so now I have to pass them thought the constructor and since it then creates a new personalization and there are no functions to replace or change that personalization, it's no longer possible to add subsitutions to the first personalization.

#### Technical details:

* sendgrid-php Version: 7.2.0
* PHP Version: 7.2

**Comment by thinkingserious** [comment]
Hi @RaoulWernert,

What's the [use case](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md) you are trying to achieve? Maybe there is an easier way, using the updated [use cases](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md).

Otherwise, I think we would need to create a `setPersonalization` method to allow for arbitrary manipulation of pre-created `Personalization` objects.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @RaoulWernert,

Did you find a solution?

Thanks!

**Comment by RaoulWernert** [comment]
I was able to clear the Personalisation array by setting the public varible
as new array

**Comment by thinkingserious** [comment]
Thanks for letting us know @RaoulWernert!
