### ISSUE TITLE
Require conformance to style standards

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-php#702]
#### Issue Summary

In the `CONTRIBUTING.md` file there is a section on Style Guidelines & Naming Conventions. Please review and implement a check in Travis CI. If there are any style errors, either fix or create a rule to exclude the error.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* TravisCI checks that the code conforms to our Style Guidelines & Naming Conventions as defined in our `CONTRIBUTING.md` file
* tests pass locally, in Travis CI and using Docker

**Comment by geryjuhasz** [comment]
@thinkingserious CI will fail if I add this. Should I also look into fixing the formatting problems inside this issue ?

**Comment by jmauerhan** [comment]
It looks like adding the namespace change in Sendgrid.php is failing the build, too. I don't see the line length changes in @GeoffYoung's PR.

**Comment by peter279k** [comment]
I agrree with @jmauerhan, these PRs are different, but they're related to this issue.

**Comment by thinkingserious** [comment]
Thanks for responding so quickly @jmauerhan and @peter279k!

**Comment by GeoffYoung** [comment]
I specified psr-2 because it was linked in `CONTRIBUTING.md`, but since I'm not using the `phpcs.xml` file already in the repo I didn't check for, or fix, the lower severity problems like the 120 character line length.

I've also introduced the namespace error that broke the unit tests with my resolution of the `SendGrid.php` check

Since those issues are already fixed in @jmauerhan's branch I thank that's going to be the better PR to accept.
