### ISSUE TITLE
#1647050 Api key doesn't have permission. Please help to rectify issue

### ISSUE THREAD

**Issue by onmytap** [sendgrid/sendgrid-php#731]
I almost tried every possible way to send mail from sendgird but always get 401. Can you help me out on this??

**Comment by thinkingserious** [comment]
Hello @onmytap,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
