### ISSUE TITLE
How to send email with attachment via SMTP not API

### ISSUE THREAD

**Issue by VirendraArekar** [sendgrid/sendgrid-php#791]
I am able to send email with smtp using codeigniter but unable to send email with attachment via sendgrid please help me

**Comment by thinkingserious** [comment]
Hello @VirendraArekar,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
