### ISSUE TITLE
CURL with No response after sending email successfully

### ISSUE THREAD

**Issue by hurkan-sert** [sendgrid/sendgrid-php#801]
$curl = curl_init();

                    curl_setopt_array($curl, array(
                      CURLOPT_URL => "https://api.sendgrid.com/v3/mail/send",
                      CURLOPT_RETURNTRANSFER => true,
                      CURLOPT_ENCODING => "",
                      CURLOPT_MAXREDIRS => 10,
                      CURLOPT_TIMEOUT => 30,
                      CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                      CURLOPT_CUSTOMREQUEST => "POST",
                      CURLOPT_POSTFIELDS => $data,
                      CURLOPT_HTTPHEADER => array(
                        "Authorization: Bearer $sendgrid_apikey  ",
                        
                        "Content-Type:application/json"
                      ),
                    ));
                    
                    $response = curl_exec($curl);
                    $err = curl_error($curl);
                    $this->log->yaz($response);
                    curl_close($curl);
                    if ($err) {
                        echo "cURL Error #:" . $err;
                      } else {
                        echo $response;
                      }

**Comment by peter279k** [comment]
It looks like it doesn't use the `sendgrid-php` library.

And this issue is not related to this repository.

**Comment by thinkingserious** [comment]
Hello @hurkan-sert,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
