### ISSUE TITLE
Leverage existing libraries rather than custom code

### ISSUE THREAD

**Issue by damienmckenna** [sendgrid/sendgrid-php#802]
#### Issue Summary

In the interest of interoperability with systems already installed on sites, rewrite the library to use Guzzle instead of the custom php-http-client library. guzzlehttp/guzzle is used by many other libraries and platforms, using a custom HTTP client is rather redundant, it would have been better to build upon guzzle or collaborating to make it a better library rather than writing your own.

**Comment by thinkingserious** [comment]
Hello @damienmckenna,

The custom HTTP client we wrote is just a thin layer on top of the native PHP HTTP client. We chose to discontinue support for Guzzle due to numerous incompatibility issues with various frameworks. Since we removed Guzzle support, those issues have gone away.

With Best Regards,

Elmer
