### ISSUE TITLE
"Mail opened" and "Spam reports" statuses are not working on sendgrid dashboard

### ISSUE THREAD

**Issue by mashooquecs** [sendgrid/sendgrid-php#810]
Hello, 
I've used sendgrid API using PHP. 
**"Opened" and "Spam reports"**  are not being updating on Sendgrid dashboard, although "Request", "Delivered" and "Clicked"  data points are updated each time I send mail with PHP.
Could any one tell me what should I do for that?

Thanks in Advance..

**Comment by thinkingserious** [comment]
Hello @mashooquecs,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
