### ISSUE TITLE
server time out

### ISSUE THREAD

**Issue by maddy2018** [sendgrid/sendgrid-php#825]
My client has a website on Joomla. We are facing the email notification issue. Neither admin nor customer getting an email for placed order.

We are using sendgrid, swiftmailer for mail purpose. We tried testing SMTP credentials through Joomla server section of test mail. Those credentials working fine.

But when we are applying the same credentials into the code, we are facing the issue of server time out. We want to resolve this issue ASAP.

I am not sure but I think it might be because of updates of swift or other plugins related to it.

* PHP Version: 5.6 Stable

Its saying - **Connection to smtp.sendgrid.net:465 Timed Out**

Any help would appreciated.

**Comment by thinkingserious** [comment]
Hello @maddy2018,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
