### ISSUE TITLE
Remove TLS using Send Grid API V3

### ISSUE THREAD

**Issue by waqaransari** [sendgrid/sendgrid-php#829]
How to remove TLS using send apiv3, i don't need it cause of email not reaching to the recipients.

**Comment by thinkingserious** [comment]
Hello @waqaransari,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
