### ISSUE TITLE
unable to fetch sendgrid email activity using PHP curl

### ISSUE THREAD

**Issue by veerendraceipal** [sendgrid/sendgrid-php#833]
#### Issue Summary

I am trying to get email activity of sub user account of SendGrid
I am trying to get emails/messages using API key

Below is the sample code:

         $curl = curl_init();
         curl_setopt_array($curl, array(
         CURLOPT_URL => "https://api.sendgrid.com/v3/messages? 
          limit=10&query=to_email%3D%22myemail%40gmail.com%22",
         CURLOPT_RETURNTRANSFER => true,
         CURLOPT_ENCODING => "",
         CURLOPT_MAXREDIRS => 10,
         CURLOPT_TIMEOUT => 30,
         CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
         CURLOPT_CUSTOMREQUEST => "GET",
         CURLOPT_POSTFIELDS => "{}",
         CURLOPT_HTTPHEADER => array(
             "authorization: Bearer SG.XXXXXXXXXXX"
         ),
   ));

   $response = curl_exec($curl);
   $err = curl_error($curl);
   curl_close($curl);

   if ($err) {
      echo "cURL Error #:" . $err;
   } else {
      echo $response;
   }

  But I am getting below response:

  {
      "errors": [
      {
        "message": "authorization required"
      }
      ]
  }

   I am mensioning that I am trying to get SendGrid sub user account sent email activity

##Technical details:
* sendgrid-php Version: master 
* PHP Version: 5.6, 7.0, 7.1, 7.2 (as of May 17, 2018)

**Comment by thinkingserious** [comment]
Hello @veerendraceipal,

Work on officially supporting that endpoint for this SDK can be [found here](https://github.com/sendgrid/sendgrid-php/issues/587).

That said, I believe that in order to get a sub user account, you need to use the [on behalf of](https://sendgrid.api-docs.io/v3.0/how-to-use-the-sendgrid-v3-api/on-behalf-of) header.

With Best Regards,

Elmer
