### ISSUE TITLE
Connection refused from laravel framework

### ISSUE THREAD

**Issue by Aubynj** [sendgrid/sendgrid-php#846]
#### Issue Summary

I have been working sendgrid API for a while now and i notice that it work perfectly when i run my project in Laravel locally. But when i upload those files to the Cpanel, it create an error report from storage folder of the log directory **Connection could not be established with host smtp.sendgrid.net [Connection refused #111] {"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host smtp.sendgrid.net [Connection refused #111] at /home/treaconc/TreaLara/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269)**. 
Is it a problem that is relate to the framework or it a problem from sendgrid. Or am i doing something wrong? 

Even though i have follow all the documentation on sendgrid for the laravel project, i think it getting a bit wierd. The funny thing is that, it was working initially and all of a sudden this problem start coming up.

**Comment by thinkingserious** [comment]
Hello @Aubynj,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by rassemdev** [comment]
It might be hosting problem. I used godaddy server, they blocked smtp relay server in general. So it might be the same case. (I might be wrong). But i recommand you should dig into your cpanel server..

**Comment by thinkingserious** [comment]
Thanks for helping out @rassemdev!
