### ISSUE TITLE
Guzzle\Http\Exception\CurlException: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: [url] https://api.sendgrid.com/api/mail.send.json'

### ISSUE THREAD

**Issue by massarogi** [sendgrid/sendgrid-php#847]
#### Issue Summary

We started receiving this error in New Relic as of 24 hours ago on our Sendgrid integration. It's only occurred about 60 times out of thousands upon thousands of emails sent from our system using Sendgrid, but we are trying to figure out what the cause of the issue is. 

Error message
Guzzle\Http\Exception\CurlException: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: [url] https://api.sendgrid.com/api/mail.send.json' in /home/user/public_html/vendor/sendgrid-php/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php:359

#### Technical details:

* sendgrid-php Version: 3.2
* PHP Version: 7.2.7

**Comment by thinkingserious** [comment]
Hi @massarogi,

I think your issue may be due to a rate limiting issue, please see [this tread](https://github.com/sendgrid/sendgrid-php/issues/173) for details.

Also, I'd recommend you update to the latest version of this SDK since we no longer have a third party dependency for the HTTP Client, [we now simply use the native PHP libraries](https://github.com/sendgrid/php-http-client/blob/master/lib/Client.php).

With Best Regards,

Elmer
