### ISSUE TITLE
Any way to use Opt-In when adding an email?

### ISSUE THREAD

**Issue by alvarotrigo** [sendgrid/sendgrid-php#855]
#### Issue Summary

I would like to have users to verify they want to subscribe when they subscribe from a form in my site.
This way I can also get rid of fake subscribes and invalid emails (typos etc).

In Mailchimp it is so easy as passing the parameter:
 ```php
'status'        => 'pending'
``` 

But I found no way to do this with Sendgrid.

**Comment by thinkingserious** [comment]
Hello @alvarotrigo,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
