### ISSUE TITLE
Personalizations result in 502

### ISSUE THREAD

**Issue by thehandcoder** [sendgrid/sendgrid-php#856]
#### Issue Summary

I'm working on sending emails with personalizations, and they are resulting in a 502.  I can connect and send emails fine when I send them without the personalization, but when I add the personalization I get a 502 from the sendgrid api

#### Steps to Reproduce

```
use \SendGrid\Mail\Personalization;
use \SendGrid\Mail\Mail;
use \SendGrid\Mail\To;
use \SendGrid;

$email = new Mail();
$email->setFrom("bubba@gump.com", "Bubba Gump");
$email->setSubject("Sending with Twilio SendGrid is Fun");
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent("text/html", "<strong>{{firstName}} and easy to do anywhere, even with PHP</strong>");

$personalization0 = new Personalization();
$personalization0->addTo(new To("sample@example.com", "Joe Schmoe"));
$personalization0->addSubstitution("firstname", "Joe");
$email->addPersonalization($personalization0);

$sendgrid = new \SendGrid('Sendgrid.key');

try {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
} catch (Exception $e) {
    echo 'Caught exception: '.  $e->getMessage(). "\n";
}
```

#### Technical details:
* sendgrid-php Version: 7.3.0
* PHP Version: 5.6

**Comment by thinkingserious** [comment]
Hello @thehandcoder,

`$personalization0->addSubstitution("firstname", "Joe");`

should be

`$personalization0->addSubstitution("{{firstname}}", "Joe");`

Thanks!

Elmer

**Comment by gwagroves** [comment]
Version: `7.3.0`

This is, IMHO, **really counter-intuitive!**

Creating a new `Mail` instance without passing any arguments [creates an empty `Personalization` instance](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L111) in the constructor.

If you subsequently add a Personalization, it is appended.

When you then send the Mail, SendGrid throws an error because **the first Personalization has no email address set**.

**Solution:** 

- Create a new `Mail` instance passing at least one argument to the constructor.
- Add Personalizations
- Set all fields (headers, etc.) _on the Personalizations_

Setting a Header using `$mail->addHeader()` before adding a Personalization [creates an empty Personalization](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L601).

So add Headers to Personalizations. But take note: `$mail->addHeader($key, $value)` has a different signature than `$personalization->addHeader(Header $header)`.

`setSubject` seems to be safe to call before addPersonalization. It then [sets the global subject](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L544).

Check the mail data by inspecting the serialized data before sending the request to SendGrid.

**Comment by childish-sambino** [comment]
Duplicates https://github.com/sendgrid/sendgrid-php/issues/686
