### ISSUE TITLE
Use and Installation

### ISSUE THREAD

**Issue by bizactuator** [sendgrid/sendgrid-php#883]
#### Issue Summary

Do I just upload these files into a folder?
Or do I have to install it via Shell?

#### Steps to Reproduce

N/A

Just trying to figure out how to use these files. I have never used sendgrid until now.

#### Technical details:

* sendgrid-php Version: master Current release
* PHP Version: 7.3

**Comment by bizactuator** [comment]
Okay, I just uploaded the files to the public_html of my domain and tried to run the code to use it...
got this error: PHP Fatal error:  require(): Failed opening required '/home/path/public_html/sendgrid-php-master/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/path/public_html/sendgrid-php-master/sendgrid-php.php on line 2

there is no vendor folder in the sengrid-php-master folder...

So how do I use this?

Thanks,
-Richard

**Comment by bizactuator** [comment]
used code from here: https://sendgrid.com/docs/for-developers/sending-email/v3-php-code-example/

**Comment by Robin-the-Frog** [comment]
Hi bizactuator
Have you given up on this? I just spent about a week going round and round in circles trying to get it installed in my new web app. No-one was being any help, either SG support ticket, or in here. I finally worked it out after hours of frustration, googling and trying things.
I was thinking of recording a video on how I did it, but it won't be quite yet
Robin

**Comment by JRadagast** [comment]
@Robin-the-Frog could you tell me what you did? i'm trying to manually install it and its not working no matter what i do.

**Comment by Robin-the-Frog** [comment]
Hi @JRadagast 
Sorry, I never got a chance to record the video.
It was quite complicated in the end and I'm not sure how easy it would be to get all the necessaries down quickly.
But... most important is how you're planning on using sendgrid? Is it a web application on someone else's hosted servers? Or your own servers?

**Comment by JRadagast** [comment]
Someone else's server, using an ajax call from a javascript method.

**Comment by Robin-the-Frog** [comment]
Hi @JRadagast 

OK, so this is what I did (briefly)…
1. I'm not using Composer
2. Mine's also not my server so I don't have access to the Shell
There appears to be 2 versions of the source files. The version on here and the version I downloaded from a link on the SG website (claiming to be the most recent as well). My instructions below work for my with the link I used (not the downlaod from here)! I did get it to work with the download from here but there are some changes necessary. Comment again and I'll try and remember what they are!!
So...
1. download zip file to your computer
2. extract and upload to your server. I saved them into a folder that I called 'sendgrid' within my public_html folder. It appears that a number of the files in the download are not actually necessary for the system to work, but I've just included everything just in case.
3. next I verified my servers within SG (go to app.sendgrid.com, log-in, then choose Settings > Sender Authentication in the left-hand menu). Just follow the instructions.
4. then, start simple and add complexity
5. grab the basic 'send an email' php code and add it to a .php page
6. If, like me, you're not using Composer, you'll need to make the require statement at the top like this
`require("sendgrid/sendgrid-php.php");` 
change the path to match yours but keeping the sendgrid-php.php the same at the end
7. I save my API key (set one in your SG account - Settings > API Keys) as a session variable so the line looks like this
`$sendgrid = new \SendGrid($_SESSION['test_api_key']);`
8. Hard-code an email address to send to
9. Upload the page to your server
10. Visit the page in your browser and see what happens. A code 202 means success. You should recieve the email and you should be able to track the email in your SG account.
11. At this point I suggest turning on sandbox mode
`$email->enableSandBoxMode();`
so you can test making the basic email more complicated (use a template, add in php $ variables instead of hard-coded values, try cc and bcc, etc etc
11. I learnt the hard way that you can't send an email, and cc or bcc the same address (as a test of cc'ing) (see issue 900 in here!)
12. If that all works, then you've got a basic email up and working. Now time to tweak, chamge, test etc

I'm up to the point now where I have emails sending fine to various addresses, using a Transactional Template, and my web-app recording the results of the send into my database. It's taken a while ( and lots of testing and frustration!) to get there though!!

Hope this works for you
Robin

**Comment by JRadagast** [comment]
Thanks, i'll try it out.

**Comment by thinkingserious** [comment]
Hello @bizactuator,

I believe your include should look like this:

```php
// using SendGrid's PHP Library
// https://github.com/sendgrid/sendgrid-php
require("./sendgrid-php.php"); // Adjust the path here to where your `sendgrid-php.php` file is located. 
```

Since you are not using Composer, you can remove this line: `require 'vendor/autoload.php';`

@Robin-the-Frog,

Thanks for helping out!!!

With best regards,

Elmer
