### ISSUE TITLE
Error 401 response with a false body and array with an empty string as headers

### ISSUE THREAD

**Issue by RaoulWernert** [sendgrid/sendgrid-php#903]
I received a weired responsethursday 31 of october  at 10:00 a.m. UTC+1while using the v3 api:
` {"\u0000*\u0000statusCode":401,"\u0000*\u0000body":false,"\u0000*\u0000headers":[""]}`
It seems to work again later that day

**Comment by thinkingserious** [comment]
Hello @RaoulWernert,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
