### ISSUE TITLE
Unable to give auto or 100% in the template container 

### ISSUE THREAD

**Issue by madanpragada4** [sendgrid/sendgrid-php#910]
I am not able to enter 100% or auto width in the following picture.
![image](https://user-images.githubusercontent.com/57802696/69049490-fc3ac880-0a25-11ea-9a51-5957a0e410ae.png)

**Comment by thinkingserious** [comment]
Hello @madanpragada4,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
