### ISSUE TITLE
Methods for work with marketing

### ISSUE THREAD

**Issue by billizzard** [sendgrid/sendgrid-php#915]
API has method https://api.sendgrid.com/v3/contactdb/lists
And this method always return in Postman (i used API key)
`{
    "errors": [
        {
            "field": null,
            "message": "access forbidden"
        }
    ]
}`

And the bundle does the same. May be  it is because it's legacy endpoint.

Also API has method https://api.sendgrid.com/v3/marketing/lists
In Postman it works well.
But bundle don't have a method for work with it.
How I can manage marketings with this bundle?

#### Technical details:

* sendgrid-php Version: "sendgrid/sendgrid": "^7.3",
* PHP Version: 7.3

**Comment by kampalex** [comment]
This can be an issue with API key permissions.
Maybe it has selected option 'Restricted access' and 'Marketing Campaigns' isn't enabled.

Tried myself. After creating a new API key without the permission enabled, I got the same error. After enabling I got `{"lists":[]}` with HTTP status 200.
The requests for `/marketing/lists` don't work for me. Also when having 'Full access'.

**Comment by devsi** [comment]
Its definitely because of legacy. I checked and I have no access to legacy endpoints that haven't been carried forward. What I don't understand is why SendGrid is still on v3/ even though **v3** is technically a completely different API. There are no GitHub docs for the current API. You have to look it up on their reference page and use the fluent accessors to make a call like 

`$sg->client->marketing()->contacts()->get()`

Nice that it works, but stupid that I spent so long trying to figure out nothing worked but just to find out the API docs don't represent the API at all.

Worse still. there appears to be a tonne of stuff missing from the new marketing endpoints. I have no way of accessing all contacts by a given list. I want to retrieve all contacts within list A, but I cannot do that, I have to retrieve ALL contacts, then just filter through them manually.

And ideas why this is such a mess?

**Comment by devsi** [comment]
omg I found it: https://sendgrid.com/docs/API_Reference/api_v3.html

They want you to run a query yourself:

```json
{
  "query": "email LIKE 'ENTER_COMPLETE_OR_PARTIAL_EMAIL_ADDRESS_HERE%' AND CONTAINS(list_ids, 'YOUR_LIST_IDs')"
}
```

**Comment by billizzard** [comment]
Thank you. I did not guess to build requests on the fly, even if they are not in the class Client.
$sg->client->marketing()->lists()->get() work well.

**Comment by devsi** [comment]
If its any help. Here is what I did to get a list by it's name, followed by all contacts in that list:

```php
$name = 'App Users';

// get lists, search by name, and use the index to fetch the list item.
$lists = $sg->marketing()->lists()->get();
$index = array_search($name, array_column($lists, 'name'));
$list = $lists[$index];

// get the list item ID and use it to generate a query for all contacts within that list.
$query = "CONTAINS(list_ids, '" . $list['id'] . "')";
$contacts = $sg->marketing()->contacts()->search()->post(compact('query'));
```

Note, this does not include formatting the response.
