### ISSUE TITLE
Marketing campaign issue

### ISSUE THREAD

**Issue by AttaurrehmaanBhatti687** [sendgrid/sendgrid-php#924]
I am creating a marketing campaign but it is not working and returning this error (errors field null message authorization required).

This is my code:
```
$curl = curl_init();
// Set some options - we are passing in a useragent too here
curl_setopt_array($curl, [
CURLOPT_RETURNTRANSFER => 1,
CURLOPT_URL => 'https://api.sendgrid.com/v3/campaigns',
CURLOPT_USERAGENT => 'Codular Sample cURL Request',
CURLOPT_POST => 1,
CURLOPT_POSTFIELDS => [
'title' => 'March Newsletter',
'subject' => 'New Products for Spring!',
'sender_id' => '',
'list_ids' => array("", ""),
'segment_ids' => array(""),
'categories' => array("spring line"),
'suppression_group_id' => 0,
'custom_unsubscribe_url' => '',
'ip_pool' => 'marketing',
'html_content' => '<title></title>

Check out our spring line!

',
'plain_content' => 'Check out our spring line!',
]
]);
// Send the request & save response to $resp
$resp = curl_exec($curl);
// Close request to clear up some resources
curl_close($curl);
```

Please clear about list_ids, segment_ids, sender_id, suppression_group_id

**Comment by kampalex** [comment]
Does your code actually worked before?

According to `Sendgrid\Client` - which is in different [repository](https://github.com/sendgrid/php-http-client/blob/master/lib/Client.php#L365) - the body part will be JSON encoded.
Also, no headers are added in your curl options which having the `Authorization: Bearer (apiKey)`, as seen [here](https://github.com/sendgrid/sendgrid-php/blob/master/lib/SendGrid.php#L43). This causes the `authorization required` error. If you fix this, you might get `bad request` due to the unknown input you provided.

Install this package locally using composer and try to execute your requests while debugging.
Put a breakpoint in file `vendor/sendgrid/php-http-client/lib/Client.php` at method `makeRequest` before `curl_setopt_array($channel, $options);`. Then you can see what you need to compose your custom code. Hopefully it will work for you.

**Comment by AttaurrehmaanBhatti687** [comment]
I am trying first time through documentations of sendgrid please provide complete guide for creating a campaign in php/codeigniter.

**Comment by kampalex** [comment]
I'm not using the campaigns part of Sendgrid, but [this library example](https://github.com/sendgrid/sendgrid-php/blob/master/examples/campaigns/campaigns.php) offers multiple scenarios - as in `complete guide` you're asking for.

**Comment by AttaurrehmaanBhatti687** [comment]
Read these examples but can,t understand how to pass these params list_ids, segment_ids, sender_id, suppression_group_id

**Comment by kampalex** [comment]
Done a little bit math - helped by the (legacy?) docs:
[Suppression groups](https://sendgrid.com/docs/API_Reference/Web_API_v3/Suppression_Management/groups.html) offers suppression_group_id
[Contactdb](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html) offers list_ids and segment_ids
[Campaigns](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/campaigns.html)

But according to [this issue](https://github.com/sendgrid/sendgrid-php/issues/863), it's suggested to use 'NEW MARKETING CAMPAIGNS' in [this documentation](https://sendgrid.com/docs/API_Reference/api_v3.html).

**Comment by AttaurrehmaanBhatti687** [comment]
Ok, thanks for helping. Let me check your provided links.

**Comment by childish-sambino** [comment]
@AttaurrehmaanBhatti687 Were the provided links able to help you out?
