### ISSUE TITLE
About demo code's working result

### ISSUE THREAD

**Issue by LimeZky** [sendgrid/sendgrid-php#934]
```php
$email->addContent("text/plain", "and easy to do anywhere, even with PHP");
$email->addContent(
    "text/html", "<strong>and easy to do anywhere, even with PHP</strong>"
);
```
However, the first line code didn't work, When I opened the email, I only saw:
![image](https://user-images.githubusercontent.com/31511420/73595420-88538b00-4553-11ea-9d6c-a1df7da80232.png)
or maybe I don't know the real purpose of this line code?

**Comment by kampalex** [comment]
You can assign multiple types of 'content' onto your email to show your message.
If your email client supports HTML (and you like to view it) - it will prefer to show the 'text/html' version of your message. Otherwise the fallback 'text/plain' will be used.

You can customize both 'types of content'. The example shows 2 types of content: 'plain text' and 'HTML' (which is the 'plain text' wrapped into 'strong' tags).
A better example could be made to prevent this issue/demo confusion :)

**Comment by LimeZky** [comment]
Ok,thanks a lot.
