### ISSUE TITLE
SendGrid\Mail\Mail constructor does not use addContent correctly

### ISSUE THREAD

**Issue by paul-automox** [sendgrid/sendgrid-php#940]
### Issue Summary
Our old code was attempting to create an email object like so:

```
$email = new \SendGrid\Mail\Mail (
	$from,
	$tos,
	$subject,
	$body
);
```

However, this caused the API to return a "The content value must be a string at least one character in length." error.  Looking at the code, this is where the constructor sets the email content:

https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L162

If you look at the addContent method, it seems like one needs to specify the type first and then the value:

https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L1093

That is definitely not what the constructor is doing.

### Technical details:
* sendgrid-php version: 7.4.0
* php version: 7.3.13

**Comment by kampalex** [comment]
You must have ran into a 'missing string validation issue' caused by `$body` = (string value).
Review your code to support newer SendGrid-php version.

**Your code fix**:
Create instances (`PlainTextContent` and/or `HtmlContent`) containing the contents and bind them onto constructor parameters.
Or use method `addContent` after constructing and provide the right `MimeType` and contents.

**Context/Thoughts for fixing in SendGrid**:
According to the constructor of `Mail`, the type of `$plainTextContent` (your `$body` parameter) to provide must be an instance of `PlainTextContent` or `null`. A string value (will pass the `isset` [check](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Mail.php#L162) and) is handled incorrectly by the `addContent` method.

The 'single non-Content parameter' scenario fails due to a missing check of not having a `value` because it equals `null`. `Content` also doesn't fire a `TypeException` because it doesn't call the `setValue` method.

Possible fix scenarios:
1) Prevent assumptions, reject invalid `$type` and `$value = null` (which may be better, but may break current scripts);
```php
    public function addContent($type, $value = null)
    {
        if ($type instanceof Content) {
            $content = $type;
        } elseif (!is_string($type)) {
            throw new TypeException('$type must be string or instance of SendGrid\Mail\Content');
        } elseif (!is_string($value)) {
            throw new TypeException('$value must be string');
        } else {
            $content = new Content($type, $value);
        }
        $this->contents[] = $content;
    }
```

2) Assume 'text/plain' type, use `$type` as `$value`. If `$value` is still invalid, `TypeException` will be thrown from the `Content` constructor.
```php
    public function addContent($type, $value = null)
    {
        if ($type instanceof Content) {
            $content = $type;
        } elseif (!is_string($type)) {
            throw new TypeException('$type must be string or instance of SendGrid\Mail\Content');
        } else {
            //  If value isn't a string, use type as value
            if (!is_string($value)) {
                $value = $type;

                //  Assume 'text/plain' as type
                $type = MimeType::TEXT;
            }

            $content = new Content($type, $value);
        }
        $this->contents[] = $content;
    }
```

You mentioned the `The content value must be a string at least one character in length.` error. This means that empty valued `Content` instances are included in the API request, which may a separate issue to solve. I suggest throwing a `TypeException` when constructing `Content` if not having none/both `$type` and `$value` parameters - it will help a little bit to prevent these simple errors.
```php
    public function __construct($type = null, $value = null)
    {
        //  Evaluate presence of type and value
        $hasValue = (isset($value));
        $hasType = (isset($type));

        //  Only allow none/both parameters
        if ($hasType !== $hasValue) {
            throw new TypeException('Please provide no/both $type and $value parameters.');
        }

        //  Assign type and value (checks can be combined into single one)
        if ($hasType) {
            $this->setType($type);
        }
        if ($hasValue) {
            $this->setValue($value);
        }
    }
```

Constructing without parameters is still possible, but I consider this scenario as 'I know what I am doing'.

Real validation of having all required properties is missing. Only `null` property values will be filtered out during `jsonSerialize`. I think this is 'by design'.

Additionally: method `setType` of `Content` doesn't check for allowed values which are defined in `MimeType`. How likely is it to allow other types than `text/plain`/`text/html`? Must other types be added as `Attachment`?

**Comment by childish-sambino** [comment]
Correct, the `body` value being passed is a string and not the proper `PlainTextContent` type. Something like this should resolve your issue:
```
$email = new \SendGrid\Mail\Mail (
	$from,
	$tos,
	$subject,
	new \SendGrid\Mail\PlainTextContent($body)
);
```

Regarding how to make this cleaner in the library, I think the least intrusive way is to add type checking in the constructor:
```
        if (isset($plainTextContent)) {
            if (!$type instanceof Content) {
                throw new TypeException(
                    '$plainTextContent must be of type Content.'
                );
            }
            $this->addContent($plainTextContent);
        }
        if (isset($htmlContent)) {
            if (!$type instanceof Content) {
                throw new TypeException(
                    '$plainTextContent must be of type Content.'
                );
            }
            $this->addContent($htmlContent);
        }
```

This is probably the least-breaking solution and gets us closer to matching the expected types documented on the constructor.
