### ISSUE TITLE
Dynamic template support for Marketing emails

### ISSUE THREAD

**Issue by TVThieu0402** [sendgrid/sendgrid-php#958]
Does Sendgrid v3 API support dynamic templates for Marketing emails? I saw support for transactional but did not see it for Marketing which leads to think it's not. 

My use case: Sending notifications to user when a new video is uploaded on a site. The video will have a unique ID link. Instead of sending user a static notification of link back to site, would like to send notification back to direct media link URL

My possible workaround: each time there is a new video, we would create a new template ID and send with direct media link URL

Are there limits on how many Template IDs you can have?

Looking to understand best practices and workarounds if possible.

**Comment by thinkingserious** [comment]
Hello @TVThieu0402,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
