### ISSUE TITLE
redirect sub user to sendgrid dashboard

### ISSUE THREAD

**Issue by curious-webs** [sendgrid/sendgrid-php#983]
Can I redirect sub user from my site to sendgrid new marketing dashboard(login them via some link)

**Comment by thinkingserious** [comment]
Hello @curious-webs,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
