### ISSUE TITLE
Revoke adding contact permission from subuser for sendgrid dashboard

### ISSUE THREAD

**Issue by curious-webs** [sendgrid/sendgrid-php#988]
Is there any option that I can allow my subuser to add contacts only via api and not from sendgrid dashboard? This is because after redirecting them to sendgrid dashboard I don't want them to add/delete/update contacts/lists from sendgrid as it will be difficult to sync with my app. Any suggestions?

**Comment by thinkingserious** [comment]
Hello @curious-webs,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
