### ISSUE TITLE
Permission denied, wrong credentials

### ISSUE THREAD

**Issue by jrahma** [sendgrid/sendgrid-php#989]
Hi,

i am trying the SendGrid PHP for the first time.

I used the same code you provided and copied my API key exactly as it is but getting:

**Permission denied, wrong credentials**

here is my code:

  $sendgrid = new \SendGrid(getenv('SG.xxxxxxx'));

```
  try
  {
    $response = $sendgrid->send($email);
    print $response->statusCode() . "\n";
    print_r($response->headers());
    print $response->body() . "\n";
  }
  catch (Exception $e)
  {
    echo 'Caught exception: '. $e->getMessage() ."\n";
  }

```

**Comment by thinkingserious** [comment]
Hello @jrahma,

Since you are not using environment variables:

`$sendgrid = new \SendGrid(getenv('SG.xxxxxxx'));` becomes `$sendgrid = new \SendGrid('SG.xxxxxxx');`

That said, we recommend you utilize [environment variables](https://github.com/sendgrid/sendgrid-php#setup-environment-variables).

With best regards,

Elmer
